__include__: [
  '../dataset/iit_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/affomernet_r50vd.yml',
]

output_dir: ./output/rtdetr_r50vd_6x_iit
